export type Yacht = {
  id: string;
  name: string;
  description: string;
  images: string[];
  capacity: number;
  length: number;
  manufacturer: string;
  model: string;
  year: number;
  cabins: number;
  bathrooms: number;
  crewIncluded: boolean;
  availabilityStatus: string;
  amenities: string[];
  pricePerHour: number;
  rating: number;
  reviewCount: number;
  isFeatured: boolean;
};

export const yachts: Yacht[] = [
  {
    id: "yacht-1",
    name: "The Sovereign",
    description: "Experience the ultimate luxury aboard The Sovereign. This stunning 85-foot motor yacht offers breathtaking views of the Chicago skyline. Designed for entertaining, it features a sprawling flybridge, a custom jacuzzi, and a meticulously crafted interior with panoramic windows.",
    images: ["/placeholder-yacht-1.jpg", "/placeholder-yacht-1-interior.jpg"],
    capacity: 13,
    length: 85,
    manufacturer: "Sunseeker",
    model: "Predator 84",
    year: 2023,
    cabins: 4,
    bathrooms: 4,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Jacuzzi", "Premium Sound System", "Full Bar", "Chef's Kitchen", "Water Toys", "Wi-Fi", "Stabilizers"],
    pricePerHour: 950,
    rating: 4.9,
    reviewCount: 142,
    isFeatured: true
  },
  {
    id: "yacht-2",
    name: "Midnight Pearl",
    description: "Sleek, fast, and remarkably elegant. The Midnight Pearl is perfect for high-profile corporate events or intimate evening cruises down the Chicago River. Its deep V-hull ensures a smooth ride, while the ambient lighting sets the perfect mood after dark.",
    images: ["/placeholder-yacht-2.jpg", "/placeholder-yacht-2-interior.jpg"],
    capacity: 12,
    length: 70,
    manufacturer: "Azimut",
    model: "S7",
    year: 2022,
    cabins: 3,
    bathrooms: 3,
    crewIncluded: true,
    availabilityStatus: "Available Tomorrow",
    amenities: ["Bluetooth Audio", "Climate Control", "Sun Deck", "Swim Platform", "BBQ Grill"],
    pricePerHour: 750,
    rating: 4.8,
    reviewCount: 98,
    isFeatured: true
  },
  {
    id: "yacht-3",
    name: "Lakefront Oasis",
    description: "Designed for relaxation, the Lakefront Oasis offers a massive bow lounging area and a shaded aft deck. Whether you're sunbathing near the Playpen or enjoying a quiet sunset, this yacht provides unmatched comfort and stability.",
    images: ["/placeholder-yacht-3.jpg", "/placeholder-yacht-3-interior.jpg"],
    capacity: 12,
    length: 65,
    manufacturer: "Sea Ray",
    model: "L650 Fly",
    year: 2020,
    cabins: 3,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Flybridge", "Full Kitchen", "Sun Pads", "Premium Wi-Fi", "Snorkeling Gear"],
    pricePerHour: 600,
    rating: 4.7,
    reviewCount: 112,
    isFeatured: false
  },
  {
    id: "yacht-4",
    name: "Aqua Marina",
    description: "A beautiful fusion of performance and luxury. Aqua Marina boasts a modern, open-plan salon that seamlessly connects to the outdoor deck. Ideal for cocktail parties and architectural tours of the city.",
    images: ["/placeholder-yacht-4.jpg", "/placeholder-yacht-4-interior.jpg"],
    capacity: 12,
    length: 58,
    manufacturer: "Princess",
    model: "F55",
    year: 2021,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Booked Today",
    amenities: ["Retractable Roof", "Wet Bar", "Ice Maker", "Lounge Seating", "Bluetooth Audio"],
    pricePerHour: 550,
    rating: 4.6,
    reviewCount: 85,
    isFeatured: false
  },
  {
    id: "yacht-5",
    name: "The Grandeur",
    description: "Step aboard The Grandeur for an unparalleled charter experience. With three spacious decks, a dedicated crew of four, and bespoke catering options, this is the premier choice for weddings, milestones, and elite gatherings.",
    images: ["/placeholder-yacht-5.jpg", "/placeholder-yacht-5-interior.jpg"],
    capacity: 25,
    length: 110,
    manufacturer: "Benetti",
    model: "Classic 121",
    year: 2019,
    cabins: 5,
    bathrooms: 6,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Helipad", "On-deck Master Suite", "Jacuzzi", "Tender Garage", "Gym Equipment", "Zero Speed Stabilizers"],
    pricePerHour: 1500,
    rating: 5.0,
    reviewCount: 34,
    isFeatured: true
  },
  {
    id: "yacht-6",
    name: "Windy City Express",
    description: "Fast and furious. The Windy City Express is a high-performance luxury cruiser perfect for quick trips up the coast to Navy Pier or zipping out to the Playpen in style. Features aggressive styling and twin V8 engines.",
    images: ["/placeholder-yacht-6.jpg", "/placeholder-yacht-6-interior.jpg"],
    capacity: 8,
    length: 45,
    manufacturer: "Pershing",
    model: "5X",
    year: 2023,
    cabins: 1,
    bathrooms: 1,
    crewIncluded: false,
    availabilityStatus: "Available Tomorrow",
    amenities: ["High Speed", "Sport Seats", "Premium Audio", "Sunbed", "Swim Ladder"],
    pricePerHour: 400,
    rating: 4.8,
    reviewCount: 56,
    isFeatured: false
  },
  {
    id: "yacht-7",
    name: "Skyline Symphony",
    description: "Enjoy harmonious moments on the Skyline Symphony. This catamaran offers incredible width and stability, providing massive deck space for dancing, dining, and mingling while taking in the Chicago skyline.",
    images: ["/placeholder-yacht-7.jpg", "/placeholder-yacht-7-interior.jpg"],
    capacity: 20,
    length: 60,
    manufacturer: "Sunreef",
    model: "60 Power",
    year: 2022,
    cabins: 4,
    bathrooms: 4,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Catamaran Stability", "Wide Beam", "Al Fresco Dining", "Grill", "Underwater Lights"],
    pricePerHour: 800,
    rating: 4.9,
    reviewCount: 77,
    isFeatured: true
  },
  {
    id: "yacht-8",
    name: "The Platinum",
    description: "A testament to Italian craftsmanship, The Platinum features exquisite woodwork, marble finishes, and a state-of-the-art entertainment system. Perfect for impressing clients or celebrating in ultimate luxury.",
    images: ["/placeholder-yacht-8.jpg", "/placeholder-yacht-8-interior.jpg"],
    capacity: 12,
    length: 75,
    manufacturer: "Riva",
    model: "76 Perseo",
    year: 2021,
    cabins: 3,
    bathrooms: 3,
    crewIncluded: true,
    availabilityStatus: "Booked Today",
    amenities: ["Mahogany Finishes", "Gourmet Kitchen", "Surround Sound", "Lounge", "Water Toys"],
    pricePerHour: 1100,
    rating: 4.9,
    reviewCount: 45,
    isFeatured: false
  },
  {
    id: "yacht-9",
    name: "Blue Horizon",
    description: "Escape the city bustle aboard Blue Horizon. This yacht is designed with expansive glass panels that flood the interior with natural light, offering 360-degree views of Lake Michigan from the comfort of an air-conditioned cabin.",
    images: ["/placeholder-yacht-9.jpg", "/placeholder-yacht-9-interior.jpg"],
    capacity: 12,
    length: 50,
    manufacturer: "Galeon",
    model: "500 Fly",
    year: 2020,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Fold-down Balconies", "Rotating Aft Seat", "Panoramic Windows", "Wi-Fi", "Mini Bar"],
    pricePerHour: 450,
    rating: 4.5,
    reviewCount: 130,
    isFeatured: false
  },
  {
    id: "yacht-10",
    name: "Starlight Cruiser",
    description: "Ideal for romantic evenings or small family outings. The Starlight Cruiser is nimble, elegantly appointed, and features a retractable sunroof that lets you gaze at the stars as you cruise the calm lake waters.",
    images: ["/placeholder-yacht-10.jpg", "/placeholder-yacht-10-interior.jpg"],
    capacity: 6,
    length: 40,
    manufacturer: "Tiara",
    model: "C39",
    year: 2018,
    cabins: 1,
    bathrooms: 1,
    crewIncluded: false,
    availabilityStatus: "Available Today",
    amenities: ["Retractable Sunroof", "Galley", "Air Conditioning", "Bluetooth Audio"],
    pricePerHour: 300,
    rating: 4.7,
    reviewCount: 210,
    isFeatured: false
  },
  {
    id: "yacht-11",
    name: "The Majestic",
    description: "With its commanding presence and timeless design, The Majestic is a floating palace. It features an expansive upper deck perfect for corporate speeches, sunset toasts, and watching the Navy Pier fireworks.",
    images: ["/placeholder-yacht-11.jpg", "/placeholder-yacht-11-interior.jpg"],
    capacity: 13,
    length: 90,
    manufacturer: "Ocean Alexander",
    model: "28R",
    year: 2022,
    cabins: 4,
    bathrooms: 5,
    crewIncluded: true,
    availabilityStatus: "Available Tomorrow",
    amenities: ["Expansive Flybridge", "Wet Bar", "Luxury Lounge", "Chef Service", "Wi-Fi"],
    pricePerHour: 1200,
    rating: 5.0,
    reviewCount: 22,
    isFeatured: true
  },
  {
    id: "yacht-12",
    name: "Silver Wave",
    description: "The Silver Wave combines sporty agility with lavish comfort. The cockpit is designed for socializing, featuring deep, plush seating and a state-of-the-art sound system that keeps the party going.",
    images: ["/placeholder-yacht-12.jpg", "/placeholder-yacht-12-interior.jpg"],
    capacity: 10,
    length: 55,
    manufacturer: "Fairline",
    model: "Targa 53",
    year: 2019,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Sport Handling", "Premium Audio", "Sunbed", "Swim Platform"],
    pricePerHour: 500,
    rating: 4.6,
    reviewCount: 88,
    isFeatured: false
  },
  {
    id: "yacht-13",
    name: "River Queen",
    description: "Specifically designed to navigate the intricate waterways of the Chicago River while providing a five-star experience. The River Queen offers a completely enclosed, climate-controlled main deck for year-round cruising.",
    images: ["/placeholder-yacht-13.jpg", "/placeholder-yacht-13-interior.jpg"],
    capacity: 12,
    length: 60,
    manufacturer: "Cruisers Yachts",
    model: "60 Cantius",
    year: 2021,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Booked Today",
    amenities: ["Climate Control", "River Capable", "Glass Enclosure", "Bar", "Lounge Seating"],
    pricePerHour: 650,
    rating: 4.8,
    reviewCount: 145,
    isFeatured: false
  },
  {
    id: "yacht-14",
    name: "Eclipse",
    description: "A dark, mysterious, and incredibly luxurious vessel. Eclipse turns heads wherever it goes. The interior is outfitted with dark woods and white leather, providing a stunning contrast perfect for VIP events.",
    images: ["/placeholder-yacht-14.jpg", "/placeholder-yacht-14-interior.jpg"],
    capacity: 12,
    length: 68,
    manufacturer: "Prestige",
    model: "680",
    year: 2022,
    cabins: 3,
    bathrooms: 3,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["VIP Cabin", "Flybridge", "Water Toys", "Premium Sound", "Grill"],
    pricePerHour: 700,
    rating: 4.9,
    reviewCount: 63,
    isFeatured: true
  },
  {
    id: "yacht-15",
    name: "Summer Breeze",
    description: "Light, airy, and inviting. The Summer Breeze is all about daytime fun on Lake Michigan. Equipped with paddleboards, a giant floating lily pad, and an outdoor BBQ, it's the ultimate Playpen party boat.",
    images: ["/placeholder-yacht-15.jpg", "/placeholder-yacht-15-interior.jpg"],
    capacity: 12,
    length: 48,
    manufacturer: "Sea Ray",
    model: "470 Sundancer",
    year: 2017,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Lily Pad", "Paddleboards", "BBQ Grill", "Sun Deck", "Coolers"],
    pricePerHour: 350,
    rating: 4.7,
    reviewCount: 312,
    isFeatured: false
  },
  {
    id: "yacht-16",
    name: "The Odyssey",
    description: "For those who demand space and opulence. The Odyssey features multiple dining areas, a massive sun deck, and a master stateroom that rivals five-star hotel suites. Perfect for weekend getaways to New Buffalo or Saugatuck.",
    images: ["/placeholder-yacht-16.jpg", "/placeholder-yacht-16-interior.jpg"],
    capacity: 12,
    length: 82,
    manufacturer: "Sunseeker",
    model: "Manhattan 82",
    year: 2020,
    cabins: 4,
    bathrooms: 4,
    crewIncluded: true,
    availabilityStatus: "Available Tomorrow",
    amenities: ["Extended Cruising", "Multiple Decks", "Jacuzzi", "Chef Service", "Tender"],
    pricePerHour: 1000,
    rating: 4.9,
    reviewCount: 41,
    isFeatured: false
  },
  {
    id: "yacht-17",
    name: "Golden Hour",
    description: "Named for the stunning reflections it catches at sunset, Golden Hour is an elegant motor yacht with sweeping lines. It features a custom teak deck and a state-of-the-art stabilizing system ensuring a perfect ride.",
    images: ["/placeholder-yacht-17.jpg", "/placeholder-yacht-17-interior.jpg"],
    capacity: 10,
    length: 52,
    manufacturer: "Absolute",
    model: "52 Fly",
    year: 2023,
    cabins: 3,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Teak Deck", "Stabilizers", "Flybridge", "Wet Bar"],
    pricePerHour: 550,
    rating: 4.8,
    reviewCount: 29,
    isFeatured: false
  },
  {
    id: "yacht-18",
    name: "Velocity",
    description: "A thrill-seeker's dream. Velocity is one of the fastest luxury charters in Chicago. When you want to feel the wind in your hair while sipping vintage champagne, this is the only choice.",
    images: ["/placeholder-yacht-18.jpg", "/placeholder-yacht-18-interior.jpg"],
    capacity: 8,
    length: 42,
    manufacturer: "VanDutch",
    model: "40",
    year: 2021,
    cabins: 1,
    bathrooms: 1,
    crewIncluded: false,
    availabilityStatus: "Available Today",
    amenities: ["High Speed", "Minimalist Design", "Premium Audio", "Champagne Cooler"],
    pricePerHour: 450,
    rating: 4.6,
    reviewCount: 104,
    isFeatured: true
  },
  {
    id: "yacht-19",
    name: "The Diplomat",
    description: "Understated elegance meets modern technology. The Diplomat offers a refined, quiet interior perfect for business meetings or intimate proposals. The crew provides discreet, white-glove service.",
    images: ["/placeholder-yacht-19.jpg", "/placeholder-yacht-19-interior.jpg"],
    capacity: 12,
    length: 64,
    manufacturer: "Princess",
    model: "V65",
    year: 2019,
    cabins: 3,
    bathrooms: 3,
    crewIncluded: true,
    availabilityStatus: "Booked Today",
    amenities: ["Quiet Cabin", "White-glove Service", "Premium Wi-Fi", "Lounge", "Climate Control"],
    pricePerHour: 750,
    rating: 4.9,
    reviewCount: 88,
    isFeatured: false
  },
  {
    id: "yacht-20",
    name: "Lake Voyager",
    description: "Built for endurance and comfort, the Lake Voyager provides a classic yachting aesthetic with beautiful wooden accents and a traditional maritime feel. Excellent for architectural tours and leisurely afternoon cruising.",
    images: ["/placeholder-yacht-20.jpg", "/placeholder-yacht-20-interior.jpg"],
    capacity: 12,
    length: 53,
    manufacturer: "Grand Banks",
    model: "Eastbay 54",
    year: 2016,
    cabins: 2,
    bathrooms: 2,
    crewIncluded: true,
    availabilityStatus: "Available Today",
    amenities: ["Classic Woodwork", "Stable Hull", "Air Conditioning", "Galley"],
    pricePerHour: 400,
    rating: 4.5,
    reviewCount: 176,
    isFeatured: false
  }
];

export const experiences = [
  {
    id: "exp-1",
    title: "Navy Pier Fireworks Cruise",
    description: "Enjoy a front-row seat to Chicago's iconic Wednesday and Saturday night fireworks display from the comfort of a luxury yacht. Avoid the crowds and watch the sky light up over Lake Michigan with a glass of champagne in hand.",
    image: "/placeholder-exp-fireworks.jpg",
    priceStartingAt: 1200,
    durationHours: 3
  },
  {
    id: "exp-2",
    title: "The Playpen VIP Party",
    description: "Experience the ultimate summer party at Chicago's famous Playpen. We drop anchor in the city's premier boating hotspot, complete with water toys, a premium sound system, and VIP bottle service upon request.",
    image: "/placeholder-exp-playpen.jpg",
    priceStartingAt: 900,
    durationHours: 4
  },
  {
    id: "exp-3",
    title: "Chicago River Architecture Tour",
    description: "A bespoke architectural tour guided by your captain. Glide down the Chicago River at sunset and marvel at the historic skyscrapers and modern marvels from an exclusive, private vantage point.",
    image: "/placeholder-exp-river.jpg",
    priceStartingAt: 800,
    durationHours: 2
  },
  {
    id: "exp-4",
    title: "Executive Sunset Dinner",
    description: "Impress your clients or celebrate a milestone with a curated private dinner on the water. Features a private chef, bespoke menu, and a gentle cruise along the skyline as the sun sets.",
    image: "/placeholder-exp-dinner.jpg",
    priceStartingAt: 2500,
    durationHours: 4
  },
  {
    id: "exp-5",
    title: "Michigan Coast Getaway",
    description: "A full-day excursion along the coast. Escape the city and cruise up to the beautiful shores of New Buffalo or St. Joseph. Includes a catered lunch, water sports, and endless relaxation.",
    image: "/placeholder-exp-coast.jpg",
    priceStartingAt: 4500,
    durationHours: 8
  }
];

export const reviews = [
  {
    id: "rev-1",
    yachtId: "yacht-1",
    customerName: "Eleanor V.",
    rating: 5,
    comment: "Absolutely phenomenal experience aboard The Sovereign. The crew was incredibly attentive, and the yacht itself was pristine. Cruising down the Chicago River at sunset was magical.",
    date: "2025-08-15"
  },
  {
    id: "rev-2",
    yachtId: "yacht-5",
    customerName: "Marcus T.",
    rating: 5,
    comment: "We booked The Grandeur for a corporate retreat, and it exceeded every expectation. The catering was five-star, and the sheer size of the yacht allowed our team of 20 to relax in ultimate comfort.",
    date: "2025-07-22"
  },
  {
    id: "rev-3",
    yachtId: "yacht-15",
    customerName: "Sarah K.",
    rating: 4,
    comment: "Summer Breeze was perfect for my bachelorette party! We spent the whole afternoon at the Playpen. The captain was fun and accommodating. Highly recommend for a girls' day out.",
    date: "2025-09-02"
  },
  {
    id: "rev-4",
    yachtId: "yacht-2",
    customerName: "David L.",
    rating: 5,
    comment: "The Midnight Pearl is a stunner. We chartered it for my wife's 40th birthday. The deep V-hull made for a very smooth ride even though the lake was slightly choppy. Five stars all the way.",
    date: "2025-06-10"
  },
  {
    id: "rev-5",
    yachtId: "yacht-7",
    customerName: "Jessica W.",
    rating: 5,
    comment: "The catamaran stability of the Skyline Symphony cannot be overstated. None of our guests felt seasick, and the deck space is unbelievable for a yacht of this length.",
    date: "2025-08-30"
  },
  {
    id: "rev-6",
    yachtId: "yacht-18",
    customerName: "Anthony R.",
    rating: 4,
    comment: "Velocity is seriously fast. We blasted out of the harbor and had an amazing time. The interior is minimal but extremely chic. Exactly the Miami-vibe we were looking for in Chicago.",
    date: "2025-07-04"
  }
];
